### ISSUE TITLE
Discussion on Docker rate limit 

### ISSUE THREAD

**Issue by furkatgofurov7** [metal3-io/project-infra#166]
Recently, we have started experiencing Docker rate limit issues:
`toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
make: *** [Makefile:4: install_requirements] Error 1`

in our [CI runs](https://jenkins.nordix.org/view/Airship/job/airship_master_v1a3_integration_test_ubuntu/410/console) and in [integration test runs](https://github.com/metal3-io/baremetal-operator/pull/719#issuecomment-729144134) in the pull requests. Possible ways as discussed in the metal3 community meeting could be: 

- setup an intermediate private registry
- make use of harbor instance in Nordix (https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/)

**Comment by furkatgofurov7** [comment]
/cc @maelk @andfasano @fmuyassarov @kashifest @zaneb @dhellmann @russellb 

to have a single place where we can start the discussion on the issue.

**Comment by dhellmann** [comment]
Do we have a list of the images that are being pulled from docker hub?

**Comment by furkatgofurov7** [comment]
@dhellmann afaik, we pull only `docker registry image` from docker hub.

**Comment by fmuyassarov** [comment]
Apart from the registry image we also pull:

- Golang image in [CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/blob/abf009beb7b2b6334f805f3fd15ba45ca14baecf/Dockerfile#L16) and [BMO](https://github.com/metal3-io/baremetal-operator/blob/cce662996fb63d1638c121502149480610163af9/Dockerfile#L2)
- Centos8 in [Ironic images](https://github.com/metal3-io/ironic-image/blob/2f7b6bd5fb5f1da3785e8e471b5467e99897f53b/Dockerfile#L4) and [vbmc](https://github.com/metal3-io/metal3-dev-env/blob/9e3ba5cfc243e68dc61dd2fe6a541dc6c0ccb30e/resources/vbmc/Dockerfile#L1) image
- Python in [sushy-tools](https://github.com/metal3-io/metal3-dev-env/blob/9e3ba5cfc243e68dc61dd2fe6a541dc6c0ccb30e/resources/sushy-tools/Dockerfile#L1) image

**Comment by dhellmann** [comment]
What do folks think about mirroring some of those image to quay ourselves until their owners publish copies of them somewhere other than docker hub?

**Comment by maelk** [comment]
We can do that, and add a job in Jenkins / Prow to keep them in sync. Works for me!

**Comment by maelk** [comment]
what is the base for the keepalived image btw ? Ubuntu, no ?

**Comment by fmuyassarov** [comment]
True, we are using ubuntu for the the keepalived image. Though, distroless image is hosted in the google container registry.

**Comment by fmuyassarov** [comment]
I just realized after @dhellmann question in https://github.com/metal3-io/baremetal-operator/pull/733#discussion_r534139002 that we are pulling more images from Docker Hub, which we use in our linter CI jobs.

- registry.hub.docker.com/securego/gosec:latest
- registry.hub.docker.com/pipelinecomponents/markdownlint:latest
- registry.hub.docker.com/koalaman/shellcheck-alpine:stable
- registry.hub.docker.com/r/garethr/kubeval - _for the future manifests linter job_

**Comment by fmuyassarov** [comment]
One more set of images that we might need to mirror could be Calico images. We are using Calico in our integration CI to set up networking for the target cluster. And this morning we saw one of the jobs failed with the following error while downloading the Calico images.

`  Warning  Failed     8m6s (x2 over 8m32s)    kubelet            Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.17.0": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit `

I just checked the [calico.yaml](https://docs.projectcalico.org/manifests/calico.yaml) that we using in [Metal3-dev-env](https://github.com/metal3-io/metal3-dev-env/blob/d0a41985dd5f97e7aab0816ea5dd749b92bce36b/vm-setup/roles/v1aX_integration_test/tasks/verify.yml#L44) and saw that we are pulling 

- docker.io/calico/cni:v3.17.0
- docker.io/calico/pod2daemon-flexvol:v3.17.0
- docker.io/calico/node:v3.17.0
- docker.io/calico/kube-controllers:v3.17.0

**Comment by fmuyassarov** [comment]
For now, the list of the images we know that we are pulling from the Docker Hub:
1. docker.io/registry:latest
2. registry.hub.docker.com/library/golang:1.15.3
3. docker.io/centos:centos8
4. registry.hub.docker.com/library/python:3.9
5. ubuntu
6. registry.hub.docker.com/securego/gosec:latest
7. registry.hub.docker.com/pipelinecomponents/markdownlint:latest
8. registry.hub.docker.com/koalaman/shellcheck-alpine:stable
9. registry.hub.docker.com/r/garethr/kubeval
10. docker.io/calico/cni:v3.17.0
11. docker.io/calico/pod2daemon-flexvol:v3.17.0
12. docker.io/calico/node:v3.17.0
13. docker.io/calico/kube-controllers:v3.17.0

**Comment by maelk** [comment]
This turns out to be a far wider issue than expected :/ Maybe we should start moving with the docker registry proxy option for metal3-dev-env, that would already remove a lot of those issues.

**Comment by andfasano** [comment]
> This turns out to be a far wider issue than expected :/ Maybe we should start moving with the docker registry proxy option for metal3-dev-env, that would already remove a lot of those issues.

Just to clarify, proxied to a private registry?

**Comment by maelk** [comment]
Well it's not really private, it is the nordix registry, so everybody could pull from there, but our goal is to modify it only for the CI, to allow people that are running their env far from Sweden to not have to download their images from Nordix.

**Comment by fmuyassarov** [comment]
Just an update:
@Xenwar is working on solution in [#587](https://github.com/metal3-io/metal3-dev-env/pull/587)  to avoid the issue by using registry cache in Nordix.

**Comment by fmuyassarov** [comment]
Final update: Using registry cache didn't go well due to the limitation of registries configuration for docker. Worked fine for podman. 

We are now prepulling container images, so avoid the need of pulling it from Docker Hub during the CI run.

Before explaining the final workaround, I will give some context about the image building jobs. We have two sets of images used in every CI run.

1. Jenkins CI image, or where we clone metal3-dev-env and run make. This image could be either Centos or Ubuntu
2. Node image, which is used for the target cluster, or by the libvirt in metal3-dev-env. This also can be either [Ubuntu](https://github.com/metal3-io/metal3-dev-env/blob/989958a4b6bf74328d1937d68fa2b510ec734265/lib/images.sh#L7) or [Centos](https://github.com/metal3-io/metal3-dev-env/blob/989958a4b6bf74328d1937d68fa2b510ec734265/lib/images.sh#L16).
 
For both two sets above, we have configured two Jenkins jobs to build images periodically. Jenkins images [(1) ](https://jenkins.nordix.org/view/Airship/job/airship_openstack_image_building/)are pushed to the CityCloud (OpenStack infra) where the CI is running. Node images [(2)](https://jenkins.nordix.org/view/Airship/job/airship_openstack_node_image_building/) are pushed to the [Artifactory](https://artifactory.nordix.org/artifactory/airship/images/).

Now back to the Docker issue. We have identified the list of the container images that we use for every integration CI run, and differentiated which ones we need to be present on the Jenkins image (1) - where we run source k8s cluster, and those needed to be present in Node image (2) - for the target cluster.  

In the source cluster, or Jenkins Image (1)

1. docker.io/registry:latest
2. registry.hub.docker.com/library/golang:1.15.3
3. docker.io/centos:centos8
4. kindest/node:v1.20.2

 
In the Node image, for the target cluster where we install Calico 

1. docker.io/calico/cni:v3.17.2
2. docker.io/calico/pod2daemon-flexvol:v3.17.2
3. docker.io/calico/node:v3.17.2
4. docker.io/calico/kube-controllers:v3.17.2

 
Note: There are more container images we pull for k8s, both in source and target cluster. However, all the other images are stored in GCR (Google Container Registry). 

Also, all the Ironic images are stored in Quay, so we don’t need to worry about them too.


Whenever we build the Jenkins(1) & Node(2) images in Nordix, we make sure to pre-pull above mentioned container images. This way, whenever integration CI runs on any PR, it won’t run into the issue of docker hub pull rate limit, because it won’t even try to pull the image from the Docker hub since the image is locally available. We tested it yesterday in metal3-dev-env with a [fake PR](https://github.com/metal3-io/metal3-dev-env/pull/597), trying to create the rate limit issue, and see if CI doesn’t fail after. The result was okay, and we saw that other daily CI(s) have also passed even though we have already reached the limit for the next 6 hours.  

Limitation of this approach is, whenever there is a version change of a container image in any of the repos where those container images are used, then we have to also go and update the version in image building scripts in Nordix repo. Otherwise, whatever container runtime we use will try to pull the image from the Docker Hub since the latest images don't exist locally.
For now this is manual work. But we are discussing to set up some automation to keep track of the changes to those images, and if there is a version change, the automation tool will also update it in Nordix.

Another limitation is that, if there is a new container image added in metal3-dev-env or in BMO/CAPM3/Ironic repos, that will be consumed by every integration CI run, then we have to also add that image to the list of pre-pulled container images in Nordix. 

We will keep watching the CI status, but for now hopefully this will work to avoid the docker issue.

**Comment by furkatgofurov7** [comment]
Fix for the issue: https://github.com/Nordix/airship-dev-tools/pull/258

We can re-open issue always if we see it in the future again, so closing for now.

/close
